#!/usr/bin/env bash

TOGGLE_MOUSE_STATUS=$(./scripts/toggle-mouse --status)
STATE=${TOGGLE_MOUSE_STATUS:-"ON"}
LABEL="${LABEL:-"Mouse"}"

if [ "$STATE" == "ON" ]; then
    echo "$LABEL ON"
    echo "$LABEL ON"
else
    echo "$LABEL OFF"
    echo "$LABEL OFF"
    echo "#808080"
fi
