#!/usr/bin/env bash

TOGGLE_MOUSE_STATUS=$($SCRIPT_DIR/toggle-mouse --status)
STATE=${TOGGLE_MOUSE_STATUS:-"ON"}
LABEL="${LABEL:-"Mouse "}"

if [ "$STATE" == "ON" ]; then
    echo "%{F-}$LABEL ON"
else
    echo "%{F#808080}$LABEL OFF"
fi
