#!/usr/bin/env bash
ID=13
STATE=$(xinput list-props "$ID" | grep "Device Enabled" | awk '{print $4}')
POS_FILE="/tmp/mouse-toggle-last-pos"

if [ "$1" == "--status" ]; then
    if [ "$STATE" -eq 1 ]; then
        echo "ON"
    else
        echo "OFF"
    fi
    exit 0
fi

if [ "$STATE" -eq 1 ]; then
    xdotool getmouselocation --shell | grep -E 'X=|Y=' | cut -d= -f2 | tr '\n' ' ' > "$POS_FILE"

    SCREEN_WIDTH=$(xdotool getdisplaygeometry | awk '{print $1}')
    SCREEN_HEIGHT=$(xdotool getdisplaygeometry | awk '{print $2}')
    xdotool mousemove $((SCREEN_WIDTH + 200)) $((SCREEN_HEIGHT + 200))

    xinput disable "$ID"
    canberra-gtk-play -i message
    # notify-send "Mouse Disabled" "The mouse with ID $ID has been disabled."
else

    if [ -f "$POS_FILE" ]; then
        read -r X Y < "$POS_FILE"
        xdotool mousemove "$X" "$Y"
        rm "$POS_FILE"
    fi

    xinput enable "$ID"
    canberra-gtk-play -i message
    # notify-send "Mouse Enabled" "The mouse with ID $ID has been enabled."
fi
